openapi: 3.0.3
info:
  title: API Persona-Cliente - Reto Técnico NTT DATA
  version: 1.0.0
  description: >
    Microservicio principal para la gestión de Clientes. 
    Diseñado bajo el enfoque (Contract First) y Arquitectura Orientada a Eventos (EDA).
    Este servicio expone operaciones CRUD síncronas y emite eventos asíncronos mediante RabbitMQ.
  contact:
    name: Erick Bedon
    email: alexbedon44@gmail.com

servers:
  - url: http://localhost:8080/api/v1

tags:
  - name: Customers
    description: Operaciones relacionadas al mantenimiento de los clientes del banco.

paths:
  /customers:
    get:
      summary: Obtener todos los clientes
      description: Retorna un listado completo de todos los clientes activos e inactivos registrados en el banco.
      operationId: getAllCustomers
      tags: [Customers]
      responses:
        '200':
          description: Lista de clientes recuperada exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      summary: Crear un nuevo cliente
      description: >
        Registra un nuevo cliente en el sistema. Valida que la identificación no esté duplicada.
        Al finalizar exitosamente, emite el evento asíncrono `CLIENTE_CREADO` a RabbitMQ.
      operationId: customersPost
      tags: [Customers]
      requestBody:
        description: Objeto JSON con los datos obligatorios del cliente.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Cliente creado exitosamente. Retorna el objeto con su ID generado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Datos de entrada inválidos (ej. edad menor a 18, formato incorrecto).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflicto - La identificación ya existe en la base de datos.


  /customers/identification/{identification}:
    get:
      summary: Buscar cliente por Identificación
      description: Retorna la información de un cliente usando su número de identificación.
      operationId: getCustomerByIdentification
      tags: [ Customers ]
      parameters:
        - name: identification
          in: path
          description: Número de identificación del cliente
          required: true
          schema:
            type: string
            example: "1712345678"
      responses:
        '200':
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Cliente no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Actualizar un cliente existente
      description: Actualiza los datos de un cliente buscando por su identificación.
      operationId: updateCustomerByIdentification
      tags: [ Customers ]
      parameters:
        - name: identification
          in: path
          description: Número de identificación del cliente
          required: true
          schema:
            type: string
            example: "1712345678"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Cliente actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Cliente no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Eliminar un cliente
      description: Elimina un cliente buscando por su identificación.
      operationId: deleteCustomerByIdentification
      tags: [ Customers ]
      parameters:
        - name: identification
          in: path
          description: Número de identificación del cliente
          required: true
          schema:
            type: string
            example: "1712345678"
      responses:
        '204':
          description: Cliente eliminado exitosamente
        '404':
          description: Cliente no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /customers/{id}:
    get:
      summary: Buscar cliente por ID
      description: Busca y retorna la información detallada de un cliente en base a su identificador único (Clave Primaria).
      operationId: getCustomerById
      tags: [Customers]
      parameters:
        - name: id
          in: path
          description: Identificador único del cliente en la base de datos.
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Cliente encontrado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Cliente no encontrado con el ID proporcionado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


    put:
      summary: Actualizar un cliente existente
      description: >
        Actualiza los datos de un cliente. Si el estado cambia.
        Emite el evento asíncrono `CLIENTE_ACTUALIZADO` a RabbitMQ.
      operationId: updateCustomer
      tags: [Customers]
      parameters:
        - name: id
          in: path
          description: Identificador único del cliente a actualizar.
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        description: Objeto JSON con los nuevos datos del cliente.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Cliente actualizado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Cliente no encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Eliminar un cliente
      description: >
        Elimina de forma física a un cliente del sistema. 
        Emite el evento `CLIENTE_ELIMINADO` a RabbitMQ para que el microservicio de Cuentas proceda a borrar sus datos vinculados.
      operationId: deleteCustomer
      tags: [Customers]
      parameters:
        - name: id
          in: path
          description: Identificador único del cliente a eliminar.
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '204':
          description: Cliente eliminado exitosamente (No Content).
        '404':
          description: Cliente no encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Person:
      type: object
      required:
        - name
        - identification
      description: Entidad base que representa a una persona física.
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          description: ID autogenerado de la persona. No hace falta para crear un cliente, es mejor eliminar este campo.
        name:
          type: string
          pattern: "^[a-zA-Z\\s]+$"
          description: Nombre completo de la persona.
          example: "Erick Bedon"
        age:
          type: integer
          minimum: 18
          description: Edad en años. Debe ser mayor de edad.
          example: 25
        identification:
          type: string
          pattern: "^[0-9]+$"
          description: Documento de identidad. Solo números.
          example: "1712345678"
        address:
          type: string
          description: Dirección de residencia actual.
          example: "Av. Perez Guerrero, Ibarra"
        phone:
          type: integer
          description: Número de contacto principal.
          example: 991234567

    Customer:
      description: Entidad Cliente que hereda todos los atributos de Persona.
      allOf:
        - $ref: '#/components/schemas/Person'
        - type: object
          properties:
            password:
              type: string
              minLength: 5
              description: Contraseña segura
              example: "@dmin123"
            status:
              type: boolean
              default: true
              description: Estado del cliente en el banco (true=Activo, false=Inactivo).
              example: true

    ErrorResponse:
      type: object
      description: Estructura estándar para el manejo global de excepciones.
      properties:
        message:
          type: string
          description: Mensaje detallado del error.
          example: "Cliente con ID 1 no existe"
        timestamp:
          type: string
          format: date-time
          description: Fecha y hora exacta en la que ocurrió el error.
          example: "2026-02-15T12:00:00.000Z"
        code:
          type: integer
          description: Código de estado HTTP retornado.
          example: 404