-- ==========================================
-- SCRIPT DE CREACIÓN DE ESQUEMA Y DATOS
-- Base de Datos: bank_db
-- ==========================================

-- ------------------------------------------
-- 1. CREACIÓN DE TABLAS (DDL)
-- ------------------------------------------

-- Tabla: person (Entidad Base - Sin campo género)
CREATE TABLE IF NOT EXISTS person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    edad INTEGER,
    identification VARCHAR(20) UNIQUE NOT NULL,
    direccion VARCHAR(255),
    telefono VARCHAR(20)
);

-- Tabla: customer (Hereda de person)
CREATE TABLE IF NOT EXISTS customer (
    customer_id BIGINT PRIMARY KEY REFERENCES person(id),
    password VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL
);

-- Tabla: accounts (Cuentas bancarias)
CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_cuenta VARCHAR(255) UNIQUE NOT NULL,
    tipo_cuenta VARCHAR(255) NOT NULL,
    saldo_inicial NUMERIC(38, 2) NOT NULL,
    estado BOOLEAN NOT NULL,
    identificacion_cliente VARCHAR(255) NOT NULL
);

-- Tabla: movements (Movimientos de las cuentas)
CREATE TABLE IF NOT EXISTS movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP(6) NOT NULL,
    tipo_movimiento VARCHAR(255) NOT NULL,
    valor NUMERIC(38, 2) NOT NULL,
    saldo NUMERIC(38, 2) NOT NULL,
    cuenta_id BIGINT NOT NULL REFERENCES accounts(id)
);

-- ------------------------------------------
-- 2. INSERCIÓN DE DATOS INICIALES (DML)
-- ------------------------------------------

-- Insertar Persona de prueba 
INSERT INTO person (nombre, edad, identification, direccion, telefono)
VALUES ('Erick Bedon', 25, '1712345678', 'Av. Perez Guerrero, Ibarra', '991234567');

-- Insertar Cliente de prueba (Asociado a la persona con ID 1)
INSERT INTO customer (customer_id, password, status)
VALUES (1, '0dmin123', true);

-- Insertar Cuenta de prueba para ese cliente
INSERT INTO accounts (numero_cuenta, tipo_cuenta, saldo_inicial, estado, identificacion_cliente)
VALUES ('12345', 'Ahorros', 2000.00, true, '1712345678');

-- Insertar Movimiento inicial de prueba
INSERT INTO movements (fecha, tipo_movimiento, valor, saldo, cuenta_id)
VALUES (CURRENT_TIMESTAMP, 'Deposito Inicial', 2000.00, 2000.00, 1);